### ISSUE TITLE
Uncaught TypeError: Cannot read property 'url' of undefined

### ISSUE THREAD

**Issue by BrunoAlcantara** [xatom-plugins/xatom-debug-nodejs#8]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [xatom-debug-nodejs](https://github.com/xatom-plugins/xatom-debug-nodejs) package 0.9.3

### Stack Trace

Uncaught TypeError: Cannot read property 'url' of undefined

```
At /Users/Bruno/.atom/packages/xatom-debug-nodejs/node_modules/xatom-debug-chrome-base/lib/debugger.js:448

TypeError: Cannot read property 'url' of undefined
    at /packages/xatom-debug-nodejs/node_modules/xatom-debug-chrome-base/lib/debugger.js:448:48
    at Array.map (native)
    at NodeDebugger.ChromeDebuggingProtocolDebugger.getCallStack (/packages/xatom-debug-nodejs/node_modules/xatom-debug-chrome-base/lib/debugger.js:443:14)
    at /packages/xatom-debug-nodejs/node_modules/xatom-debug-chrome-base/lib/plugin.js:102:50)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
    at /packages/xatom-debug-nodejs/node_modules/xatom-debug-chrome-base/lib/debugger.js:139:46)
    at emitOne (events.js:96:13)
    at DebuggerDomain.emit (events.js:188:7)
    at ChromeDebuggingRequester.responseHandler (/packages/xatom-debug-nodejs/node_modules/chrome-debugging-protocol/lib/chrome-debugging-requester.js:49:42)
    at /packages/xatom-debug-nodejs/node_modules/chrome-debugging-protocol/lib/chrome-debugging-requester.js:20:19)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at Receiver._receiver.onmessage (/packages/xatom-debug-nodejs/node_modules/ws/lib/WebSocket.js:146:54)
    at Receiver.dataMessage (/packages/xatom-debug-nodejs/node_modules/ws/lib/Receiver.js:389:14)
    at Receiver.getData (/packages/xatom-debug-nodejs/node_modules/ws/lib/Receiver.js:330:12)
    at Receiver.startLoop (/packages/xatom-debug-nodejs/node_modules/ws/lib/Receiver.js:165:16)
    at Receiver.add (/packages/xatom-debug-nodejs/node_modules/ws/lib/Receiver.js:139:10)
    at Socket._ultron.on (/packages/xatom-debug-nodejs/node_modules/ws/lib/WebSocket.js:142:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
```

### Commands

```
```

### Non-Core Packages

```
atom-jade 0.3.0 
atom-pug 0.2.0 
atom-runner 2.7.1 
file-icons 2.1.9 
goto-definition 1.3.4 
xatom-debug 1.6.10 
xatom-debug-nodejs 0.9.3 
```

**Comment by BrunoAlcantara** [comment]
This error still happening :-(

**Comment by BrunoAlcantara** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [xatom-debug-nodejs](https://github.com/xatom-plugins/xatom-debug-nodejs) package 0.9.3


### Stack Trace

Uncaught TypeError: Cannot read property 'url' of undefined

```
At /Users/Bruno/.atom/packages/xatom-debug-nodejs/node_modules/xatom-debug-chrome-base/lib/debugger.js:448

TypeError: Cannot read property 'url' of undefined
    at /packages/xatom-debug-nodejs/node_modules/xatom-debug-chrome-base/lib/debugger.js:448:48
    at Array.map (native)
    at NodeDebugger.ChromeDebuggingProtocolDebugger.getCallStack (/packages/xatom-debug-nodejs/node_modules/xatom-debug-chrome-base/lib/debugger.js:443:14)
    at /packages/xatom-debug-nodejs/node_modules/xatom-debug-chrome-base/lib/plugin.js:102:50)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
    at /packages/xatom-debug-nodejs/node_modules/xatom-debug-chrome-base/lib/debugger.js:139:46)
    at emitOne (events.js:96:13)
    at DebuggerDomain.emit (events.js:188:7)
    at ChromeDebuggingRequester.responseHandler (/packages/xatom-debug-nodejs/node_modules/chrome-debugging-protocol/lib/chrome-debugging-requester.js:49:42)
    at /packages/xatom-debug-nodejs/node_modules/chrome-debugging-protocol/lib/chrome-debugging-requester.js:20:19)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at Receiver._receiver.onmessage (/packages/xatom-debug-nodejs/node_modules/ws/lib/WebSocket.js:146:54)
    at Receiver.dataMessage (/packages/xatom-debug-nodejs/node_modules/ws/lib/Receiver.js:389:14)
    at Receiver.getData (/packages/xatom-debug-nodejs/node_modules/ws/lib/Receiver.js:330:12)
    at Receiver.startLoop (/packages/xatom-debug-nodejs/node_modules/ws/lib/Receiver.js:165:16)
    at Receiver.add (/packages/xatom-debug-nodejs/node_modules/ws/lib/Receiver.js:139:10)
    at Socket._ultron.on (/packages/xatom-debug-nodejs/node_modules/ws/lib/WebSocket.js:142:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
```

### Commands

```
     -1:20 core:backspace (input.hidden-input)
  2x -1:18.5.0 core:move-up (input.hidden-input)
     -1:18 editor:select-to-end-of-line (input.hidden-input)
  3x -1:17.7.0 core:backspace (input.hidden-input)
  3x -1:16 core:move-up (input.hidden-input)
     -1:15.3.0 core:move-down (input.hidden-input)
     -1:15 core:backspace (input.hidden-input)
  6x -1:14.6.0 core:move-up (input.hidden-input)
     -1:13.6.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -1:13.3.0 editor:select-to-first-character-of-line (input.hidden-input)
  2x -1:13 core:backspace (input.hidden-input)
     -1:10.6.0 core:save (input.hidden-input)
     -0:26.4.0 core:copy (input.hidden-input)
     -0:24.3.0 find-and-replace:show (input.hidden-input)
     -0:24 core:paste (input.hidden-input)
  4x -0:23.3.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-jade 0.3.0 
atom-pug 0.2.0 
atom-runner 2.7.1 
file-icons 2.1.10 
goto-definition 1.3.4 
xatom-debug 1.6.11 
xatom-debug-nodejs 0.9.3 
```

**Comment by brunoliveiralcantara** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.3 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [xatom-debug-nodejs](https://github.com/xatom-plugins/xatom-debug-nodejs) package 0.9.3


### Stack Trace

Uncaught TypeError: Cannot read property 'url' of undefined

```
At /Users/Bruno/.atom/packages/xatom-debug-nodejs/node_modules/xatom-debug-chrome-base/lib/debugger.js:448

TypeError: Cannot read property 'url' of undefined
    at /packages/xatom-debug-nodejs/node_modules/xatom-debug-chrome-base/lib/debugger.js:448:48
    at Array.map (native)
    at NodeDebugger.ChromeDebuggingProtocolDebugger.getCallStack (/packages/xatom-debug-nodejs/node_modules/xatom-debug-chrome-base/lib/debugger.js:443:14)
    at /packages/xatom-debug-nodejs/node_modules/xatom-debug-chrome-base/lib/plugin.js:102:50)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
    at /packages/xatom-debug-nodejs/node_modules/xatom-debug-chrome-base/lib/debugger.js:139:46)
    at emitOne (events.js:96:13)
    at DebuggerDomain.emit (events.js:188:7)
    at ChromeDebuggingRequester.responseHandler (/packages/xatom-debug-nodejs/node_modules/chrome-debugging-protocol/lib/chrome-debugging-requester.js:49:42)
    at /packages/xatom-debug-nodejs/node_modules/chrome-debugging-protocol/lib/chrome-debugging-requester.js:20:19)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at Receiver._receiver.onmessage (/packages/xatom-debug-nodejs/node_modules/ws/lib/WebSocket.js:146:54)
    at Receiver.dataMessage (/packages/xatom-debug-nodejs/node_modules/ws/lib/Receiver.js:389:14)
    at Receiver.getData (/packages/xatom-debug-nodejs/node_modules/ws/lib/Receiver.js:330:12)
    at Receiver.startLoop (/packages/xatom-debug-nodejs/node_modules/ws/lib/Receiver.js:165:16)
    at Receiver.add (/packages/xatom-debug-nodejs/node_modules/ws/lib/Receiver.js:139:10)
    at Socket._ultron.on (/packages/xatom-debug-nodejs/node_modules/ws/lib/WebSocket.js:142:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
```

### Commands

```
     -4:03.4.0 find-and-replace:show (input.hidden-input)
  3x -4:00.1.0 core:confirm (input.hidden-input)
     -2:10 find-and-replace:show (input.hidden-input)
     -2:08.6.0 editor:consolidate-selections (input.hidden-input)
     -2:08.6.0 core:cancel (input.hidden-input)
     -0:53.8.0 core:close (input.hidden-input)
     -0:37.9.0 core:cancel (button.btn.btn-default)
```

### Non-Core Packages

```
atom-jade 0.3.0 
atom-pug 0.2.0 
atom-runner 2.7.1 
atom-sass 0.4.0 
atom-typescript 11.0.7 
busy-signal 1.4.3 
file-icons 2.1.11 
goto-definition 1.3.4 
grunt-runner 0.14.0 
intentions 1.1.5 
jshint 1.8.6 
linter 2.2.0 
linter-ui-default 1.6.7 
xatom-debug 1.6.11 
xatom-debug-nodejs 0.9.3 
```
